# Generated by Django 2.1.2 on 2018-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('tamano', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('fechaRescate', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='D', max_length=1)),
            ],
        ),
    ]
