# Generated by Django 2.1.2 on 2018-10-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='fechaRescate',
            field=models.DateTimeField(),
        ),
    ]
