# Generated by Django 2.1.2 on 2018-11-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0002_auto_20181030_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='peso',
            field=models.FloatField(),
        ),
    ]
