# Generated by Django 2.1.2 on 2018-11-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0003_auto_20181107_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='tamano',
            field=models.FloatField(),
        ),
    ]
