# Generated by Django 2.1.2 on 2018-11-08 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0004_auto_20181107_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='tamano',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
