# Generated by Django 2.1.2 on 2018-11-08 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0005_auto_20181107_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='perritos',
            name='tamano',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2, 5)]),
        ),
    ]
