# Generated by Django 2.1.2 on 2018-11-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0006_auto_20181108_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perritos',
            name='fechaRescate',
            field=models.DateField(),
        ),
    ]
