# Generated by Django 2.1.2 on 2018-11-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerritos', '0007_auto_20181111_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritos',
            name='fechaRescate',
            field=models.DateTimeField(),
        ),
    ]
